"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.contributions_api import ContributionsApi  # noqa: E501


class TestContributionsApi(unittest.TestCase):
    """ContributionsApi unit test stubs"""

    def setUp(self):
        self.api = ContributionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contributions_health(self):
        """Test case for contributions_health

        Checking the health of the contributions service  # noqa: E501
        """
        pass

    def test_create_contribution(self):
        """Test case for create_contribution

        Create a new contribution  # noqa: E501
        """
        pass

    def test_create_resolution(self):
        """Test case for create_resolution

        Resolve a contribution  # noqa: E501
        """
        pass

    def test_get_contributions(self):
        """Test case for get_contributions

        Get contributions  # noqa: E501
        """
        pass

    def test_get_contributions_by_id(self):
        """Test case for get_contributions_by_id

        Get contribution by Id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
