"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_review201_response import CreateReview201Response


class TestCreateReview201Response(unittest.TestCase):
    """CreateReview201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateReview201Response(self):
        """Test CreateReview201Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateReview201Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
