"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.applications_api import ApplicationsApi  # noqa: E501


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_application(self):
        """Test case for create_application

        Create a new application  # noqa: E501
        """
        pass

    def test_create_contribution_type(self):
        """Test case for create_contribution_type

        Create a new contribution type  # noqa: E501
        """
        pass

    def test_get_application_by_id(self):
        """Test case for get_application_by_id

        Get application by Id  # noqa: E501
        """
        pass

    def test_get_applications(self):
        """Test case for get_applications

        Get applications  # noqa: E501
        """
        pass

    def test_get_contribution_type_by_name(self):
        """Test case for get_contribution_type_by_name

        Get contribution type by name  # noqa: E501
        """
        pass

    def test_get_contribution_types(self):
        """Test case for get_contribution_types

        Get contributionTypes  # noqa: E501
        """
        pass

    def test_update_contribution_type_by_name(self):
        """Test case for update_contribution_type_by_name

        Update contribution type by name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
