"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.review_config import ReviewConfig
globals()['ReviewConfig'] = ReviewConfig
from openapi_client.model.contribution_type_response import ContributionTypeResponse


class TestContributionTypeResponse(unittest.TestCase):
    """ContributionTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContributionTypeResponse(self):
        """Test ContributionTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContributionTypeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
