"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.reviews_api import ReviewsApi  # noqa: E501


class TestReviewsApi(unittest.TestCase):
    """ReviewsApi unit test stubs"""

    def setUp(self):
        self.api = ReviewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contributions_health(self):
        """Test case for contributions_health

        Checking the health of the contributions service  # noqa: E501
        """
        pass

    def test_create_review(self):
        """Test case for create_review

        Create a new review  # noqa: E501
        """
        pass

    def test_get_reviews_by_contribution(self):
        """Test case for get_reviews_by_contribution

        Get reviews for a contribution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
