"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_contribution_type201_response import CreateContributionType201Response


class TestCreateContributionType201Response(unittest.TestCase):
    """CreateContributionType201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateContributionType201Response(self):
        """Test CreateContributionType201Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateContributionType201Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
