"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.review_response import ReviewResponse


class TestReviewResponse(unittest.TestCase):
    """ReviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReviewResponse(self):
        """Test ReviewResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReviewResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
