# coding: utf-8

"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ReviewConfig(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "reviewerAmount",
            "reviewPolicy",
        }
        
        class properties:
        
            @staticmethod
            def reviewPolicy() -> typing.Type['ReviewPolicy']:
                return ReviewPolicy
            reviewerAmount = schemas.IntSchema
            __annotations__ = {
                "reviewPolicy": reviewPolicy,
                "reviewerAmount": reviewerAmount,
            }
    
    reviewerAmount: MetaOapg.properties.reviewerAmount
    reviewPolicy: 'ReviewPolicy'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reviewPolicy"]) -> 'ReviewPolicy': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reviewerAmount"]) -> MetaOapg.properties.reviewerAmount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["reviewPolicy", "reviewerAmount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reviewPolicy"]) -> 'ReviewPolicy': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reviewerAmount"]) -> MetaOapg.properties.reviewerAmount: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["reviewPolicy", "reviewerAmount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        reviewerAmount: typing.Union[MetaOapg.properties.reviewerAmount, decimal.Decimal, int, ],
        reviewPolicy: 'ReviewPolicy',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReviewConfig':
        return super().__new__(
            cls,
            *args,
            reviewerAmount=reviewerAmount,
            reviewPolicy=reviewPolicy,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.review_policy import ReviewPolicy
