# coding: utf-8

"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.applications.post import CreateApplication
from openapi_client.paths.applications_application_id_contribution_types.post import CreateContributionType
from openapi_client.paths.applications_application_id.get import GetApplicationById
from openapi_client.paths.applications.get import GetApplications
from openapi_client.paths.applications_application_id_contribution_types_name.get import GetContributionTypeByName
from openapi_client.paths.applications_application_id_contribution_types.get import GetContributionTypes
from openapi_client.paths.applications_application_id_contribution_types_name.put import UpdateContributionTypeByName


class ApplicationsApi(
    CreateApplication,
    CreateContributionType,
    GetApplicationById,
    GetApplications,
    GetContributionTypeByName,
    GetContributionTypes,
    UpdateContributionTypeByName,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
