# coding: utf-8

"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.contributions_authentication.post import AuthTokenRequest
from openapi_client.paths.health.get import ContributionsHealth
from openapi_client.paths.contributions.post import CreateContribution
from openapi_client.paths.contributions_contribution_id_resolutions.post import CreateResolution
from openapi_client.paths.contributions_find_by_reviewer_id.get import FindByReviewerId
from openapi_client.paths.contributions.get import GetContributions
from openapi_client.paths.contributions_contribution_id.get import GetContributionsById


class ContributionsApi(
    AuthTokenRequest,
    ContributionsHealth,
    CreateContribution,
    CreateResolution,
    FindByReviewerId,
    GetContributions,
    GetContributionsById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
