# coding: utf-8

"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.applications_application_id_contribution_types_name.options import ApplicationsApplicationIdContributionTypesNameOptions
from openapi_client.paths.applications_application_id_contribution_types.options import ApplicationsApplicationIdContributionTypesOptions
from openapi_client.paths.applications_application_id.options import ApplicationsApplicationIdOptions
from openapi_client.paths.applications.options import ApplicationsOptions
from openapi_client.paths.contributions_contribution_id.options import ContributionsContributionIdOptions
from openapi_client.paths.contributions_contribution_id_resolutions.options import ContributionsContributionIdResolutionsOptions
from openapi_client.paths.contributions_contribution_id_reviews.options import ContributionsContributionIdReviewsOptions
from openapi_client.paths.contributions_find_by_reviewer_id.options import ContributionsFindByReviewerIdOptions
from openapi_client.paths.contributions.options import ContributionsOptions


class CorsApi(
    ApplicationsApplicationIdContributionTypesNameOptions,
    ApplicationsApplicationIdContributionTypesOptions,
    ApplicationsApplicationIdOptions,
    ApplicationsOptions,
    ContributionsContributionIdOptions,
    ContributionsContributionIdResolutionsOptions,
    ContributionsContributionIdReviewsOptions,
    ContributionsFindByReviewerIdOptions,
    ContributionsOptions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
