# coding: utf-8

"""
    Hugs Platform - OpenAPI 3.0

    The Hugs Platform API  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.health.get import ContributionsHealth
from openapi_client.paths.contributions_contribution_id_reviews.post import CreateReview
from openapi_client.paths.contributions_contribution_id_reviews.get import GetReviewsByContribution


class ReviewsApi(
    ContributionsHealth,
    CreateReview,
    GetReviewsByContribution,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
